import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Exclusive Games",
  description: "Generated by Exclusive game",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Exclusive Games</title>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
